project_name: flog

builds:
  - binary: flog
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - Update README.md
    - Merge pull request
    - Merge branch

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - get-flog.sh
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - get-flog.sh

release:
  github:
    owner: wchaws
    name: flog
  name_template: '{{.Tag}}'

# brews:
#   - name: flog
#     github:
#       owner: mingrammer
#       name: homebrew-flog
#     commit_author:
#       name: mingrammer
#       email: mingrammer@gmail.com
#     homepage: https://github.com/mingrammer/flog
#     description: "A fake log generator for common log formats"
#     install: bin.install "flog"
