name: Build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - name: Build
        run: go build

